version: '3.8'

services:
  db:
    image: postgres:15
    container_name: electronics_db
    environment:
      POSTGRES_DB: electronics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Используем другой порт, чтобы не конфликтовать с локальным PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: electronics_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata network/fixtures/initial_data.json &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: electronics_db
      DB_USER: postgres
      DB_PASSWORD: postgres

  nginx:
    image: nginx:1.27-alpine
    container_name: electronics_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
